version: "3.2"


services:
    main:
        build:
          context: ./docker/main
          dockerfile: Dockerfile
        volumes:
            - './docker/main:/workspace'
        tty: true

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - '15672:15672'
            - '5672:5672'


